const GLOBAL_VARIABLE = process.env.GLOBAL_VARIABLE

function generateSiteMap(posts) {
  return `<?xml version="1.0" encoding="UTF-8"?>
   <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-agartala</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-agra</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-ahmedabad</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-ahmednagar</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-aizawl</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-ajmer</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-akola</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-aligarh</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-allahabad</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-alwar</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-ambala</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-ambarnath</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-ambattur</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-amravati</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-amritsar</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-amroha</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-anand</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-anantapur</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-anantapuram</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-arrah</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-asansol</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-aurangabad</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-avadi</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-bahraich</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-bally</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-bangalore</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-baranagar</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-barasat</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-bardhaman</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-bareilly</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-bathinda</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-begusarai</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-belgaum</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-bellary</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-berhampore</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-berhampur</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-bhagalpur</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-bhalswa-jahangir-pur</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-bharatpur</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-bhatpara</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-bhavnagar</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-bhilai</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-bhilwara</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-bhind</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-bhiwandi</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-bhiwani</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-bhopal</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-bhubaneswar</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-bhusawal</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-bidar</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-bidhannagar</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-bihar-sharif</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-bijapur</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-bikaner</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-bilaspur</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-bokaro</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-bulandshahr</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-burhanpur</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-chandigarh</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-chandrapur</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-chapra</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-chennai</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-chittoor</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-coimbatore</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-cuttack</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-darbhanga</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-davanagere</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-dehradun</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-delhi</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-deoghar</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-dewas</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-dhanbad</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-dhule</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-dindigul</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-durg</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-durgapur</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-eluru</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-erode</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-etawah</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-faridabad</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-farrukhabad</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-fatehpur</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-firozabad</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-gandhidham</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-gandhinagar</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-gaya</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-ghaziabad</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-gopalpur</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-gorakhpur</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-gulbarga</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-guntur</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-gurgaon</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-guwahati</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-gwalior</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-haldia</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-hapur</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-haridwar</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-hospet</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-howrah</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-hubli-dharwad</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-hyderabad</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-ichalkaranji</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-imphal</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-indore</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-jabalpur</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-jaipur</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-jalandhar</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-jalgaon</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-jalna</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-jammu</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-jamnagar</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-jamshedpur</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-jhansi</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-jodhpur</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-junagadh</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-kadapa</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-kakinada</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-kalyan-dombivli</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-kamarhati</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-kanpur</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-karawal-nagar</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-karimnagar</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-karnal</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-katni</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-khammam</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-khandwa</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-kharagpur</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-khora%2C-ghaziabad</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-kirari-suleman-nagar</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-kochi</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-kolhapur</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-kolkata</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-kollam</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-korba</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-kota</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-kozhikode</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-kulti</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-kurnool</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-latur</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-loni</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-lucknow</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-ludhiana</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-madhyamgram</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-madurai</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-maheshtala</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-malda</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-malegaon</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-mangalore</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-mango</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-mathura</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-mau</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-meerut</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-mira-bhayandar</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-mirzapur</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-moradabad</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-morbi</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-morena</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-mumbai</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-munger</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-muzaffarnagar</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-muzaffarpur</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-mysore</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-nadiad</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-nagercoil</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-nagpur</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-naihati</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-nanded</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-nandyal</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-nangloi-jat</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-nashik</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-navi-mumbai</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-nellore</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-new-delhi</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-nizamabad</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-noida</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-north-dumdum</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-ongole</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-orai</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-pali</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-pallavaram</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-panchkula</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-panihati</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-panipat</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-parbhani</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-patiala</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-patna</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-pimpri-chinchwad</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-pondicherry</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-pune</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-puri</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-purnia</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-raebareli</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-raichur</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-raipur</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-rajahmundry</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-rajkot</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-rajpur-sonarpur</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-ramagundam</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-rampur</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-ranchi</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-ratlam</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-rewa</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-rohtak</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-rourkela</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-sagar</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-saharanpur</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-salem</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-sambalpur</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-sambhal</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-sangli-miraj-%26-kupwad</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-satara</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-satna</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-secunderabad</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-shahjahanpur</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-shimoga</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-sikar</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-silchar</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-siliguri</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-singrauli</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-solapur</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-sonipat</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-south-dumdum</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-sri-ganganagar</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-srinagar</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-surat</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-tenali</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-thane</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-thanjavur</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-thiruvananthapuram</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-thoothukudi</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-thrissur</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-tiruchirappalli</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-tirunelveli</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-tirupati</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-tiruppur</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-tiruvottiyur</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-tumkur</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-udaipur</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-ujjain</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-ulhasnagar</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-uluberia</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-uzhavarkarai</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-vadodara</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-varanasi</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-vasai-virar</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-vijayanagaram</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-vijayawada</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-visakhapatnam</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-warangal</loc>
<lastmod>2023-12-18</lastmod>
</url>
<url>
<loc>${GLOBAL_VARIABLE}/llp-registration/llp-registration-in-yamunanagar</loc>
<lastmod>2023-12-18</lastmod>
</url>
   </urlset>
 `;
}

export default function SiteMap() { }

export async function getServerSideProps({ res }) {
  const sitemap = generateSiteMap();
  res.setHeader('Content-Type', 'text/xml');
  res.write(sitemap);
  res.end();

  return {
    props: {},
  };
}