const GLOBAL_VARIABLE = process.env.GLOBAL_VARIABLE

function generateSiteMap(pages) {
  const sitemap = pages
    .map(element =>
      `<url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-agartala</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-agra</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-ahmedabad</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-ahmednagar</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-aizawl</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-ajmer</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-akola</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-aligarh</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-allahabad</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-alwar</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-ambala</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-ambarnath</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-ambattur</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-amravati</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-amritsar</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-amroha</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-anand</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-anantapur</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-anantapuram</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-arrah</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-asansol</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-aurangabad</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-avadi</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-bahraich</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-bally</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-bangalore</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-baranagar</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-barasat</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-bardhaman</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-bareilly</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-bathinda</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-begusarai</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-belgaum</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-bellary</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-berhampore</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-berhampur</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-bhagalpur</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-bhalswa-jahangir-pur</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-bharatpur</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-bhatpara</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-bhavnagar</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-bhilai</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-bhilwara</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-bhind</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-bhiwandi</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-bhiwani</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-bhopal</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-bhubaneswar</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-bhusawal</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-bidar</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-bidhannagar</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-bihar-sharif</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-bijapur</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-bikaner</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-bilaspur</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-bokaro</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-bulandshahr</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-burhanpur</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-chandigarh</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-chandrapur</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-chapra</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-chennai</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-chittoor</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-coimbatore</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-cuttack</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-darbhanga</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-davanagere</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-dehradun</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-delhi</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-deoghar</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-dewas</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-dhanbad</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-dhule</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-dindigul</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-durg</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-durgapur</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-eluru</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-erode</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-etawah</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-faridabad</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-farrukhabad</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-fatehpur</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-firozabad</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-gandhidham</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-gandhinagar</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-gaya</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-ghaziabad</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-gopalpur</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-gorakhpur</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-gulbarga</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-guntur</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-gurgaon</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-guwahati</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-gwalior</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-haldia</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-hapur</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-haridwar</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-hospet</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-howrah</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-hubli-dharwad</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-hyderabad</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-ichalkaranji</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-imphal</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-indore</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-jabalpur</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-jaipur</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-jalandhar</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-jalgaon</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-jalna</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-jammu</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-jamnagar</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-jamshedpur</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-jhansi</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-jodhpur</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-junagadh</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-kadapa</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-kakinada</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-kalyan-dombivli</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-kamarhati</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-kanpur</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-karawal-nagar</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-karimnagar</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-karnal</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-katni</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-khammam</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-khandwa</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-kharagpur</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-khora%2C-ghaziabad</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-kirari-suleman-nagar</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-kochi</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-kolhapur</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-kolkata</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-kollam</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-korba</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-kota</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-kozhikode</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-kulti</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-kurnool</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-latur</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-loni</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-lucknow</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-ludhiana</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-madhyamgram</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-madurai</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-maheshtala</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-malda</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-malegaon</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-mangalore</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-mango</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-mathura</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-mau</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-meerut</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-mira-bhayandar</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-mirzapur</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-moradabad</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-morbi</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-morena</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-mumbai</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-munger</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-muzaffarnagar</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-muzaffarpur</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-mysore</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-nadiad</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-nagercoil</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-nagpur</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-naihati</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-nanded</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-nandyal</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-nangloi-jat</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-nashik</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-navi-mumbai</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-nellore</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-new-delhi</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-nizamabad</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-noida</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-north-dumdum</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-ongole</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-orai</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-pali</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-pallavaram</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-panchkula</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-panihati</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-panipat</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-parbhani</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-patiala</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-patna</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-pimpri-chinchwad</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-pondicherry</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-pune</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-puri</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-purnia</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-raebareli</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-raichur</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-raipur</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-rajahmundry</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-rajkot</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-rajpur-sonarpur</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-ramagundam</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-rampur</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-ranchi</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-ratlam</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-rewa</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-rohtak</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-rourkela</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-sagar</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-saharanpur</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-salem</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-sambalpur</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-sambhal</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-sangli-miraj-%26-kupwad</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-satara</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-satna</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-secunderabad</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-shahjahanpur</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-shimoga</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-sikar</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-silchar</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-siliguri</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-singrauli</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-solapur</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-sonipat</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-south-dumdum</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-sri-ganganagar</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-srinagar</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-surat</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-tenali</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-thane</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-thanjavur</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-thiruvananthapuram</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-thoothukudi</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-thrissur</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-tiruchirappalli</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-tirunelveli</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-tirupati</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-tiruppur</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-tiruvottiyur</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-tumkur</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-udaipur</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-ujjain</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-ulhasnagar</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-uluberia</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-uzhavarkarai</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-vadodara</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-varanasi</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-vasai-virar</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-vijayanagaram</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-vijayawada</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-visakhapatnam</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-warangal</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-yamunanagar</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-maharashtra</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-jharkhand</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-madhya-pradesh</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-andhra-pradesh</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-himachal-pradesh</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-tamil-nadu</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-odisha</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-assam</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-arunachal-pradesh</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-gujarat</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-chandigarh</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-jammu-and-kashmir</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-manipur</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-andaman-and-nicobar-islands</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-bihar</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-chhattisgarh</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-dadra-and-nagar-haveli</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-daman-and-diu</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-goa</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-haryana</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-kerala</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-ladakh</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-lakshadweep</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-meghalaya</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-mizoram</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-nagaland</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-punjab</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-rajasthan</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-sikkim</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-telangana</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-tripura</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-uttar-pradesh</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-uttarakhand</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    <url>
    <loc>${GLOBAL_VARIABLE}/${element.slug}/${element.slug}-in-west-bengal</loc>
    <lastmod>2023-12-18</lastmod>
    </url>
    `)
    .join('')


  return `<?xml version="1.0" encoding="UTF-8"?>
   <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
   ${sitemap}
   </urlset>
 `;
}

export default function SiteMap() { }

export async function getServerSideProps({ res }) {
  let allPosts = [];
  let page = 1;
  let totalPages = 1;
  
  while (page <= totalPages) {
    const response = await fetch(`${GLOBAL_VARIABLE}/wordpress/wp-json/wp/v2/pages?page=${page}`);
    const data = await response.json();

    allPosts = [...allPosts, ...data];

    const totalPagesHeader = response.headers.get('X-WP-TotalPages');
    if (totalPagesHeader) {
      totalPages = parseInt(totalPagesHeader);
    }
    page++;
  }

  const sitemap = generateSiteMap(allPosts);
  res.setHeader('Content-Type', 'text/xml');
  res.write(sitemap);
  res.end();

  return {
    props: {},
  };
}